CREATE DATABASE EMPRESADELIMPEZA;
USE EMPRESADELIMPEZA;

CREATE TABLE CLIENTE(
CODCLI INT NOT NULL,
NOMECLI VARCHAR(30) NOT NULL,
FONECLI VARCHAR(12),
ENDCLI VARCHAR(100) NOT NULL,
LIMCREDCLI VARCHAR(10),
STATUSCLI VARCHAR(2)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CODCLI PRIMARY KEY (CODCLI) ;
ALTER TABLE CLIENTE MODIFY FONECLI VARCHAR(12) NOT NULL;

CREATE TABLE PEDIDO (
NUMPED INT PRIMARY KEY,
DTELABPED VARCHAR(10),
CODCLI INT
);
 
 ALTER TABLE PEDIDO ADD CONSTRAINT FK_CODCLI FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI);
 
 CREATE TABLE CATEGORIA(
 CODCAT INT PRIMARY KEY,
 DESCCAT VARCHAR(15)
 );
 
 CREATE TABLE PRODUTO(
 CODPROD INT PRIMARY KEY,
 NOMEPROD VARCHAR(15) NOT NULL,
 PRECOPROD VARCHAR(10) NOT NULL,
CODCAT INT
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_CODCAT FOREIGN KEY (CODCAT) REFERENCES CATEGORIA (CODCAT);
ALTER TABLE PRODUTO MODIFY PRECOPROD DECIMAL(10,2);

CREATE TABLE PEDIDOPRODUTO(     # PESQUISEI EM FONTES ALTERNATIVAS PARA ADICIONAR DUAS PRIMARY KEYS
NUMPED INT ,
CODPROD INT ,
QTDEITEMPROD VARCHAR(4),
PRIMARY KEY (NUMPED, CODPROD),
FOREIGN KEY (NUMPED) REFERENCES PEDIDO (NUMPED),
FOREIGN KEY (CODPROD) REFERENCES PRODUTO (CODPROD)
);

DROP TABLE PEDIDOPRODUTO;

CREATE TABLE PEDIDOPRODUTO(     # PESQUISEI EM FONTES ALTERNATIVAS PARA ADICIONAR DUAS PRIMARY KEYS
NUMPED INT ,
CODPROD INT ,
QTDEITEMPROD VARCHAR(4),
PRIMARY KEY (NUMPED, CODPROD),
FOREIGN KEY (NUMPED) REFERENCES PEDIDO (NUMPED),
FOREIGN KEY (CODPROD) REFERENCES PRODUTO (CODPROD)
);

PRIMARYINSERT INTO CATEGORIA VALUES (1, 'DESINFETANTE'), (2, 'DETERGENTE'), (3, 'SABÃO EM PÓ');

-- Ajusta o tipo ANTES do insert # A partir daqui eu usei pedi para o chatGPT me ajudar pois não estava entendendo como fazer.
ALTER TABLE PRODUTO MODIFY PRECOPROD DECIMAL(10,2);

-- Agora sim: insert correto
INSERT INTO CATEGORIA VALUES 
(1, 'DESINFETANTE'), 
(2, 'DETERGENTE'), 
(3, 'SABÃO EM PÓ');

ALTER TABLE PRODUTO MODIFY NOMEPROD VARCHAR(40);

INSERT INTO PRODUTO VALUES 
(10,'Cloro Ativo',12.50,1),
(11,'Detergente Neutro',4.20,2),
(12,'Omo Progress',25.00,3);PRIMARYFK_CODCAT

INSERT INTO CLIENTE VALUES
(1,'Maria','1499990000','Rua A',300,'A'),
(2,'João','1498880000','Rua B',200,'A'),
(3,'Pedro','1497770000','Rua C',150,'I');

INSERT INTO PEDIDO VALUES
(100,'2025-10-01',1),
(101,'2025-10-02',2),
(102,'2025-10-03',3);

INSERT INTO PEDIDOPRODUTO VALUES
(100,10,2),
(101,11,5),
(102,12,1);

SELECT * FROM PEDIDOPRODUTO;
